# Setup
backend = "glx"
vsync = false;

# Transparency
active-opacity = 1;
inactive-opacity = 1;

# Fading
fading = true;
fade-delta = 3;

wintypes:
{
    dropdown_menu = { shadow = false; opacity = 1; };
    popup_menu    = { shadow = false; opacity = 1; };
    utility       = { shadow = false; opacity = 1; };
    dock          = { shadow = false; opacity = 1; };
};

